/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_register_design;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static login_register_design.Login_Form.currentUserId;

/**
 *
 * @author Lenovo
 */
public class Wallet_Form extends javax.swing.JFrame {

    /**
     * Creates new form Wallet_Form
     */
    public Wallet_Form() {
        initComponents();  
        this.setLocationRelativeTo(null); 
        
        currentBalance.setText("Balance : " + Login_Form.currentBalance);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        currentBalance = new javax.swing.JLabel();
        DepositMoneyButton = new javax.swing.JButton();
        withdrawingButton = new javax.swing.JButton();
        withdrawMoneyText = new javax.swing.JTextField();
        depositMoneyTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wallet");

        jLabel_minimize.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_minimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimize.setText(" -");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setText(" X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_close))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<< Back To Main Menu");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        currentBalance.setBackground(new java.awt.Color(0, 0, 0));
        currentBalance.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 21)); // NOI18N

        DepositMoneyButton.setBackground(new java.awt.Color(0, 0, 0));
        DepositMoneyButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        DepositMoneyButton.setForeground(new java.awt.Color(255, 255, 255));
        DepositMoneyButton.setText("Deposit Money");
        DepositMoneyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepositMoneyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepositMoneyButtonMouseExited(evt);
            }
        });
        DepositMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositMoneyButtonActionPerformed(evt);
            }
        });

        withdrawingButton.setBackground(new java.awt.Color(0, 0, 0));
        withdrawingButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        withdrawingButton.setForeground(new java.awt.Color(255, 255, 255));
        withdrawingButton.setText("Withdrawing Money");
        withdrawingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawingButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawingButtonMouseExited(evt);
            }
        });
        withdrawingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawingButtonActionPerformed(evt);
            }
        });

        withdrawMoneyText.setBackground(new java.awt.Color(255, 255, 255));
        withdrawMoneyText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        withdrawMoneyText.setForeground(new java.awt.Color(69, 73, 74));
        withdrawMoneyText.setText("$$$$.$$");
        withdrawMoneyText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                withdrawMoneyTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                withdrawMoneyTextFocusLost(evt);
            }
        });
        withdrawMoneyText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                withdrawMoneyTextKeyTyped(evt);
            }
        });

        depositMoneyTextField.setBackground(new java.awt.Color(255, 255, 255));
        depositMoneyTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        depositMoneyTextField.setForeground(new java.awt.Color(69, 73, 74));
        depositMoneyTextField.setText("$$$$.$$");
        depositMoneyTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                depositMoneyTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                depositMoneyTextFieldFocusLost(evt);
            }
        });
        depositMoneyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositMoneyTextFieldActionPerformed(evt);
            }
        });
        depositMoneyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                depositMoneyTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LEV");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("LEV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(withdrawingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(withdrawMoneyText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DepositMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositMoneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DepositMoneyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depositMoneyTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(withdrawingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addComponent(withdrawMoneyText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(9, 9, 9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepositMoneyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositMoneyButtonMouseEntered
        // TODO add your handling code here:
        
        DepositMoneyButton.setBackground(Color.blue);
        
    }//GEN-LAST:event_DepositMoneyButtonMouseEntered

    private void DepositMoneyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositMoneyButtonMouseExited
        // TODO add your handling code here:
        
               DepositMoneyButton.setBackground(Color.black);
        
    }//GEN-LAST:event_DepositMoneyButtonMouseExited

    private void withdrawingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawingButtonMouseEntered
        // TODO add your handling code here:
        
        withdrawingButton.setBackground(Color.blue);
        
    }//GEN-LAST:event_withdrawingButtonMouseEntered

    private void withdrawingButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawingButtonMouseExited
        // TODO add your handling code here:
        
        withdrawingButton.setBackground(Color.black);
        
    }//GEN-LAST:event_withdrawingButtonMouseExited

    private void DepositMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositMoneyButtonActionPerformed
        try {
            // TODO add your handling code here:
            
            Double depositMoney = Double.parseDouble(depositMoneyTextField.getText());
            
            PreparedStatement st;
            ResultSet rs;
            
            String query = "UPDATE users SET balance = balance + ? WHERE id = ?";
            
            st = My_CNX.getConnection().prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
            
            st.setDouble(1, depositMoney);
            st.setInt(2, Login_Form.currentUserId);
            System.out.println(Login_Form.currentUserId);
            System.out.println(depositMoney);
            
            if(st.executeUpdate() != 0){
                               JOptionPane.showMessageDialog(null, "To Verify Your Transaction Log In!");
                               Login_Form form = new Login_Form();
                               form.setVisible(true);
                               form.pack();
                               form.setLocationRelativeTo(null);
                               this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                        }

            
        } catch (SQLException ex) {
            Logger.getLogger(Wallet_Form.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
        }
                    
                
                
        
    }//GEN-LAST:event_DepositMoneyButtonActionPerformed

    private void depositMoneyTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_depositMoneyTextFieldFocusGained
        // TODO add your handling code here:
       
        if(depositMoneyTextField.getText().trim().toLowerCase().equals("$$$$.$$"))
        {
            depositMoneyTextField.setText("");
             depositMoneyTextField.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_depositMoneyTextFieldFocusGained

    private void depositMoneyTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_depositMoneyTextFieldFocusLost
        // TODO add your handling code here:
      
       if(depositMoneyTextField.getText().trim().equals("") ||
           depositMoneyTextField.getText().trim().toLowerCase().equals("$$$$.$$"))
        {
            depositMoneyTextField.setText("$$$$.$$");
          
             depositMoneyTextField.setForeground(new Color(69,73,74));
        }
        
        
        
       // depositMoneyTextField.setForeground(new Color(69,73,74));
        
    }//GEN-LAST:event_depositMoneyTextFieldFocusLost

    private void withdrawMoneyTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_withdrawMoneyTextFocusGained
        // TODO add your handling code here:

        if(withdrawMoneyText.getText().trim().toLowerCase().equals("$$$$.$$"))
        {
            withdrawMoneyText.setText("");
             withdrawMoneyText.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_withdrawMoneyTextFocusGained

    private void withdrawMoneyTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_withdrawMoneyTextFocusLost
        // TODO add your handling code here:
               if(withdrawMoneyText.getText().trim().equals("") ||
           withdrawMoneyText.getText().trim().toLowerCase().equals("$$$$.$$"))
        {
            withdrawMoneyText.setText("$$$$.$$");
          
             withdrawMoneyText.setForeground(new Color(69,73,74));
        }
        
        
     //   withdrawMoneyText.setForeground(new Color(69,73,74));
        
    }//GEN-LAST:event_withdrawMoneyTextFocusLost

    private void depositMoneyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositMoneyTextFieldKeyTyped
        // TODO add your handling code here:
        
            if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
            }
        
    }//GEN-LAST:event_depositMoneyTextFieldKeyTyped

    private void withdrawMoneyTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdrawMoneyTextKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_withdrawMoneyTextKeyTyped

    private void depositMoneyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositMoneyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositMoneyTextFieldActionPerformed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked

        // minimize
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        //     Border label_border = BorderFactory.createMatteBorder(1,1,1,1,new Color(0,204,255));
        //        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.red);

    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        //         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        //        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked

        // exit
        System.exit(0);

    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        //
        //         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,new Color(0,204,255));
        //         jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        //        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        //         jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        Menu_Form form = new Menu_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered

        jButton2.setBackground(new Color(51,153,0));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited

        jButton2.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void withdrawingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawingButtonActionPerformed
        // TODO add your handling code here:
        if(verifyWithdrawMoney()){
            try{        
          Double withdrawMoney = Double.parseDouble(withdrawMoneyText.getText());
            
            PreparedStatement st;
            ResultSet rs;
            
            String query = "UPDATE users SET balance = balance - ? WHERE id = ?";
            
            st = My_CNX.getConnection().prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
            
            st.setDouble(1, withdrawMoney);
            st.setInt(2, Login_Form.currentUserId);
            
           // rs = st.executeQuery();
            
            if(st.executeUpdate() != 0){
                               JOptionPane.showMessageDialog(null, "To Verify Your Transaction Log In!");
                               Login_Form form = new Login_Form();
                               form.setVisible(true);
                               form.pack();
                               form.setLocationRelativeTo(null);
                               this.dispose();
                             
                               //currentBalance.setText("Balance : " + rs.getDouble(8));
                               
                             //this.dispose();
                             
                        }else{
                            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                        }

            
        } catch (SQLException ex) {
            Logger.getLogger(Wallet_Form.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
        }
            
        }

                    
                
                
        
        
    }//GEN-LAST:event_withdrawingButtonActionPerformed

    boolean verifyWithdrawMoney(){
        double withdrownMoney = Double.parseDouble(withdrawMoneyText.getText());
        double balance = Login_Form.currentBalance;
        if(balance < withdrownMoney){
            JOptionPane.showMessageDialog(null, "Error: Non-Sufficient Funds! Your Balance: " + Login_Form.currentBalance);
            return false;  
        }else if(withdrownMoney < 0){
            JOptionPane.showMessageDialog(null, "Error: Sum must be positive");
            return false;
        }
        return true;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wallet_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DepositMoneyButton;
    private javax.swing.JLabel currentBalance;
    private javax.swing.JTextField depositMoneyTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField withdrawMoneyText;
    private javax.swing.JButton withdrawingButton;
    // End of variables declaration//GEN-END:variables
}
